name = "PyPlotHDF5"
uuid = "2ad7014a-875a-4970-86da-8d1146347de9"
authors = ["Daniel Alcalde <d.alcalde.puente@fz-juelich.de>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
